[window]
title = "Alacritty"
dimensions = { columns = 120, lines = 35 }
blur= true   

[font]
size = 10.1

[font.offset]
x = 0
y = 4

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[general]
working_directory = '~'


[terminal.shell]
program = "/bin/zsh"


[cursor]
style = "Beam"
